name: gulp
version: '${project.version}'
main: dev.gulp.gulp.Gulp
api-version: '1.20'
load: STARTUP

commands:
  gulp:
    description: "Main command for your plugin"
    usage: "/gulp <command>"
    permission: "gulp.use"